import abc
from abc import ABC, abstractmethod
from bkd.base.models.interpreter.base import ModelInterpreter
from typing import Hashable

__all__ = ['ModelABC']

class ModelABC[InT, OutT, SampleT, LikelihoodT](ABC, metaclass=abc.ABCMeta):
    interpreter: ModelInterpreter[OutT, SampleT, LikelihoodT]
    @abstractmethod
    def forward(self, ipt: InT) -> OutT: ...
    def output(self, ipt: InT) -> OutT: ...
    def ml(self, ipt: InT) -> SampleT: ...
    def sample(self, ipt: InT) -> SampleT: ...
    def log_likelihood(self, ipt: InT, target_samples: SampleT) -> LikelihoodT: ...
    @property
    @abstractmethod
    def hash(self) -> Hashable: ...
    def __hash__(self) -> int: ...
