from bkd.base.callbacks.stack import CallbackStack
from bkd.base.utils.typing.base.pydantic import RestrictedBaseModel
from bkd.base.utils.typing.eval.metrics import Metric as Metric, MetricID as MetricID, MetricStep as MetricStep, Metrics as Metrics, MetricsBatch

class BufferedMetricsStack(RestrictedBaseModel, CallbackStack):
    buffer_max_size: int
    buffer: MetricsBatch
    def check_buffer_flush(self) -> None: ...
    def flush_buffer(self) -> None: ...
    def clear_buffer(self) -> None: ...
    def start_aux(self, num_epochs: None | int = None) -> None: ...
    def log_metric(self, mid: MetricID, metric: Metric, step: MetricStep = None) -> None: ...
    def log_metrics(self, metrics: Metrics, step: MetricStep = None) -> None: ...
    def log_metrics_batch(self, batch: MetricsBatch) -> None: ...
    def close_aux(self) -> None: ...
