from bkd.base.utils.typing.eval.metrics import Metric, MetricID, MetricStep, Metrics, MetricsBatch
from bkd.base.utils.typing.events import BatchID, EpochID

__all__ = ['EventCallback']

class EventCallback:
    def start(self, num_epochs: None | int = None) -> None: ...
    def log_epoch_start(self, eid: EpochID, epoch_size: None | int = None) -> None: ...
    def log_epoch_end(self, eid: EpochID) -> None: ...
    def log_batch_start(self, bid: BatchID) -> None: ...
    def log_batch_end(self, bid: BatchID) -> None: ...
    def log_metric(self, mid: MetricID, metric: Metric, step: MetricStep = None) -> None: ...
    def log_metrics(self, metrics: Metrics, step: MetricStep = None) -> None: ...
    def log_metrics_batch(self, batch: MetricsBatch) -> None: ...
    def close(self) -> None: ...
