[project]

# Main info
name = "nml"
version = "0.1.0"

description = "Norma Multiplex Library"
readme = "README.md"

authors = [{ name = "Davide Barbieri", email = "davidebarbieri97@gmail.com" }]

# Tags
keywords = ["interface", "rl", "ml"]

classifiers = ["Programming Language :: Python :: 3.13"]

# Dependencies
requires-python = ">=3.13"
dependencies = [
  "nml-base",
  "mlflow>=3.5.1",
  "numpy>=2.3.4",
  "pydantic>=2.12.4",
  "rich>=14.2.0",
  "nml-tools-base",
  "plotly>=6.5.0",
  "kaleido>=1.2.0",
]

[dependency-groups]
config = ["nml-config-base"]
dev = [
  "hypothesis[all,numpy]>=6.147.0",
  "lxml-stubs>=0.5.1",
  "mypy>=1.18.2",
  "pandas-stubs>=2.3.2.250926",
  "pre-commit>=4.3.0",
  "pre-commit-hooks>=6.0.0",
  "pyright>=1.1.407",
  "pytest>=8.4.2",
  "pytest-cov>=7.0.0",
  "ruff>=0.14.3",
  "scipy-stubs>=1.16.3.0",
  "tox>=4.32.0",
  "types-cachetools>=6.2.0.20251022",
  "types-cffi>=1.17.0.20250915",
  "types-colorama>=0.4.15.20250801",
  "types-defusedxml>=0.7.0.20250822",
  "types-docker>=7.1.0.20251009",
  "types-greenlet>=3.2.0.20250915",
  "types-networkx>=3.5.0.20251106",
  "types-openpyxl>=3.1.5.20250919",
  "types-paramiko>=4.0.0.20250822",
  "types-pexpect>=4.9.0.20250916",
  "types-protobuf>=6.32.1.20251105",
  "types-psutil>=7.0.0.20251111",
  "types-pyasn1>=0.6.0.20250914",
  "types-pygments>=2.19.0.20250809",
  "types-pysftp>=0.2.17.20250805",
  "types-pysocks>=1.7.1.20251001",
  "types-python-dateutil>=2.9.0.20251108",
  "types-pyyaml>=6.0.12.20250915",
  "types-requests>=2.32.4.20250913",
  "types-tabulate>=0.9.0.20241207",
  "types-tensorflow>=2.18.0.20251008",
  "types-tqdm>=4.67.0.20250809",
  "types-xlrd>=2.0.0.20251020",
]
nvim = ["debugpy>=1.8.17", "pynvim>=0.6.0"]
torch = [
  "nml-itf-torch",
  "nml-tools-base",
  "nml-tools-torch",
  "torch>=2.9.0",
  "torcheval>=0.0.7",
]

# Worskapce settings
[tool.uv.sources]
nml-base = { workspace = true }
nml-itf-torch = { workspace = true }
nml-tools-torch = { workspace = true }
nml-config-base = { workspace = true }
nml-tools-base = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

# Tools

[tool.ruff.lint]
select = ["D", "D417", "I", "F401"]
ignore = [
  "D104", # docstring in public module
  "D203", # incorrect-blank-line-before-class
  "D213", # multi-line-summary-second-line
]

[tool.mypy]
namespace_packages = true
strict = true
install_types = true

disallow_untyped_calls = false

disable_error_code = "import-untyped"

files = ["packages/"]
explicit_package_bases = true
mypy_path = [
  "packages/nml-base/src",
  "packages/nml-itf-torch/src",
  "packages/nml-rl-base/src",
  "packages/nml-tools-base/src",
  "packages/nml-tools-torch/src",
  "packages/nml-config-base/src",
  "packages/nml-state/src",
]

[tool.pyright]
extraPaths = [
  "packages/nml-base/src",
  "packages/nml-itf-torch/src",
  "packages/nml-rl-base/src",
  "packages/nml-tools-base/src",
  "packages/nml-tools-torch/src",
  "packages/nml-config-base/src",
  "packages/nml-state/src",
]

# Testing

[tool.pytest.ini_options]
addopts = "-vv"

[tool.coverage.run]
branch = true

omit = ["packages/nml-base/src/nml/callbacks/ui/*"]

[tool.coverage.report]
include_namespace_packages = true
# Regexes for lines to exclude from consideration
exclude_also = [
  # Don't complain about missing debug-only code:
  "def __repr__",

  # Don't complain if tests don't hit defensive assertion code:
  "raise AssertionError",
  "raise NotImplementedError",

  # Don't complain if non-runnable code isn't run:
  "if 0:",
  "if __name__ == .__main__.:",

  # Don't complain about abstract methods, they aren't run:
  "@(abc\\.)?abstractmethod",
]
skip_empty = true
ignore_errors = true

[tool.coverage.html]
directory = ".coverage_html_report"
