[tox]
envlist = py313, coverage, codechecks, typechecking

[testenv]
skip_install = true
allowlist_externals =
  pytest
  pytest-cov
commands =
  pytest --cov=packages --cov-report=html

[testenv:coverage]
description = check that coverage is above 90%
skip_install = true
allowlist_externals =
    coverage
commands =
    coverage report --fail-under=85

[testenv:codechecks]
description = check formatting and linting of the entire package
skip_install = true
allowlist_externals =
    ruff
commands =
    ruff check package

[testenv:typechecking]
description = static type checking of package
skip_install = true
allowlist_externals =
    mypy
commands =
    mypy -p bkd.callbacks
    mypy -p bkd.data
    mypy -p bkd.loss
    mypy -p bkd.models
    mypy -p bkd.train
    mypy -p bkd.utils
    mypy -p bkd.config.shards
    mypy -p bkd.itf.torch
    mypy -p bkd.tools.torch
    mypy test
