[tox]
envlist = py313, coverage, codechecks, typechecking

[testenv]
skip_install = true
allowlist_externals =
  pytest
  pytest-cov
commands =
  pytest --cov=packages --cov-report=html

[testenv:coverage]
description = check that coverage is above 90%
skip_install = true
allowlist_externals =
    coverage
commands =
    coverage report --fail-under=85

[testenv:codechecks]
description = check formatting and linting of the entire package
skip_install = true
allowlist_externals =
    ruff
commands =
    ruff check package

[testenv:typechecking]
description = static type checking of package
skip_install = true
allowlist_externals =
    mypy
commands =
    mypy -p nml.callbacks
    mypy -p nml.data
    mypy -p nml.loss
    mypy -p nml.models
    mypy -p nml.train
    mypy -p nml.utils
    mypy -p nml.config.shards
    mypy -p nml.itf.torch
    mypy -p nml.tools.torch
    mypy test
