[tox]
envlist = py313, codechecks, typechecking

[testenv]
skip_install = true
allowlist_externals =
  pytest
commands =
  pytest

[testenv:codechecks]
description = check formatting and linting of the entire package
skip_install = true
allowlist_externals =
    ruff
commands =
    ruff check src

[testenv:typechecking]
description = static type checking of package
skip_install = true
allowlist_externals =
    mypy
commands =
    mypy -p bkd
    mypy test
