__all__ = ['ModelInterpreter']

class ModelInterpreter[ModelOutT, SampleT, LikelihoodT]:
    def output(self, model_out: ModelOutT) -> ModelOutT: ...
    def sample(self, model_out: ModelOutT) -> SampleT: ...
    def ml(self, model_out: ModelOutT) -> SampleT: ...
    def log_likelihood(self, target_samples: SampleT, model_out: ModelOutT) -> LikelihoodT: ...
