from bkd.base.callbacks.abc import EventCallback
from bkd.base.utils.mlflow.client import ExperimentClient as ExperimentClient, RunClient as RunClient
from bkd.base.utils.typing.base.pydantic import StandardBaseModel
from bkd.base.utils.typing.eval.metrics import Metric as Metric, MetricID as MetricID, MetricStep as MetricStep, Metrics as Metrics, MetricsBatch as MetricsBatch

class MLFlowMetricCallback(StandardBaseModel, EventCallback):
    client: ExperimentClient
    ephimeral_run: bool
    run_name: None | str
    current_run: None | RunClient
    def start(self, num_epochs: None | int = None) -> None: ...
    def log_metric(self, mid: MetricID, metric: Metric, step: MetricStep = None) -> None: ...
    def log_metrics(self, metrics: Metrics, step: MetricStep = None) -> None: ...
    def log_metrics_batch(self, batch: MetricsBatch) -> None: ...
    def close(self) -> None: ...
