from bkd.base.utils.typing.base.pydantic import RestrictedBaseModel
from bkd.base.utils.typing.mlflow import MLFlowDataset, MLFlowMetric, MLFlowParam, MLFlowRun, MLFlowRunTag, MLFlowTagsDict
from mlflow.client import MlflowClient
from mlflow.utils.async_logging.run_operations import RunOperations
from typing import Sequence

__all__ = ['ExperimentClient', 'RunClient']

class ExperimentClient(RestrictedBaseModel):
    experiment_id: str
    client: MlflowClient
    def create_run(self, start_time: None | int = None, tags: None | MLFlowTagsDict = None, run_name: None | str = None) -> MLFlowRun: ...
    def create_run_client(self, start_time: None | int = None, tags: None | MLFlowTagsDict = None, run_name: None | str = None) -> RunClient: ...
    def set_run_id(self, run_id: str) -> RunClient: ...

class RunClient(ExperimentClient):
    run_id: str
    @property
    def run(self) -> MLFlowRun: ...
    def log_metric(self, key: str, value: float, timestamp: None | int = None, step: None | int = None, synchronous: None | bool = None, dataset_name: None | str = None, dataset_digest: None | str = None, model_id: None | str = None) -> None | RunOperations: ...
    def log_metrics(self, metrics: dict[str, float], step: None | int = None, synchronous: None | bool = None, timestamp: None | int = None, model_id: None | str = None, dataset: None | MLFlowDataset = None) -> None | RunOperations: ...
    def log_batch(self, metrics: Sequence[MLFlowMetric] = (), params: Sequence[MLFlowParam] = (), tags: Sequence[MLFlowRunTag] = (), synchronous: None | bool = None) -> None | RunOperations: ...
